# Generated by Django 2.2.8 on 2019-12-14 15:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=12)),
                ('size', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('GBP', 'British Pound'), ('EUR', 'Euro'), ('USD', 'US Dollar')], max_length=3)),
                ('maturity', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2019, 12, 14))])),
                ('lei', models.CharField(max_length=20)),
            ],
        ),
    ]
