# Generated by Django 2.2.8 on 2019-12-14 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0002_bond_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lei', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='bond',
            name='lei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonds.LegalEntity'),
        ),
    ]
