# Generated by Django 2.2.8 on 2019-12-14 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0003_auto_20191214_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='legal_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bonds.LegalEntity'),
        ),
        migrations.AlterField(
            model_name='bond',
            name='lei',
            field=models.CharField(max_length=20),
        ),
    ]
